# Generated by Django 5.2 on 2025-04-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hindi', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('library_type', models.CharField(choices=[('public', 'Public Library'), ('academic', 'Academic Library'), ('school', 'School Library'), ('special', 'Special Library'), ('digital', 'Digital Library'), ('community', 'Community Library')], default='public', max_length=20)),
                ('establishment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi')], default='en', max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)')], default='INR', max_length=10)),
                ('date_format', models.CharField(choices=[('dd/mm/yyyy', 'DD/MM/YYYY'), ('mm/dd/yyyy', 'MM/DD/YYYY'), ('yyyy-mm-dd', 'YYYY-MM-DD'), ('dd-mm-yyyy', 'DD-MM-YYYY')], default='dd/mm/yyyy', max_length=20)),
                ('time_format', models.CharField(choices=[('12', '12-hour (AM/PM)'), ('24', '24-hour')], default='12', max_length=5)),
                ('enable_festival_calendar', models.BooleanField(default=True)),
                ('festival_categories', models.JSONField(blank=True, default=list, null=True)),
                ('enable_indian_classification', models.BooleanField(default=False)),
                ('theme_color', models.CharField(choices=[('tricolor', 'Tricolor'), ('saffron', 'Saffron'), ('green', 'Green'), ('navy', 'Navy'), ('peacock', 'Peacock'), ('lotus', 'Lotus')], default='tricolor', max_length=20)),
                ('default_mode', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System)')], default='light', max_length=10)),
                ('theme_rajasthani', models.BooleanField(default=False)),
                ('theme_kerala', models.BooleanField(default=False)),
                ('theme_varanasi', models.BooleanField(default=False)),
                ('font_family', models.CharField(choices=[('default', 'Default'), ('noto_sans', 'Noto Sans'), ('poppins', 'Poppins'), ('hind', 'Hind'), ('tiro_devanagari', 'Tiro Devanagari')], default='default', max_length=20)),
                ('border_radius', models.CharField(choices=[('default', 'Medium'), ('small', 'Small'), ('large', 'Large'), ('rounded', 'Fully Rounded')], default='default', max_length=20)),
                ('enable_animations', models.BooleanField(default=True)),
                ('enable_decorative_elements', models.BooleanField(default=True)),
                ('high_contrast_mode', models.BooleanField(default=False)),
                ('display_hours', models.BooleanField(default=True)),
                ('holidays', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='libraries.library')),
            ],
        ),
    ]
